### ISSUE TITLE
Setting up the CI/CD pipeline (better late than never...)

### ISSUE THREAD

**Issue by DEberhardt** [DEberhardt/TeamsFunctions#109]
Finally, after eons of publishing and testing in my local environment (it worked on my machine! 😉), I am finally ready to set up the pipeline. I have broken out the individual files I am running into separate files in `.\packages\testing\` for easier collaboration.

### Tasks
- [x] **Create Github Action "Powershell"**
  - [x] Find suitable example (JanDeDobbeleer's wonderful setup for `oh-my-posh` does nicely)
  - [x] Adapt source material Powershell.yml (may need more improvements)
  - [x] Adapt Module File and Module Manifest
  - [x] Adapt Deploy.ps1 (may need more improvements)
  - [x] Learn more about actions
- [ ] **Create CI Mechansim**
  - [x] Update Documentation (PlatyPs 0.14.1)
  TODO: Create Standalone action upon PR to `main`
  This currently happens as the last Commit before merging into main (and thus before publishing a release)
  It is done currently with the Function `Update-DocsAndPester`. This should become a separate action
  - [ ] Integrity Check: Module Functions (`Compare-TeamsFunctionModuleContent`)
  Have I updated the PSD1/PSM1 correctly or did I forget to add a function?
  Run Module comparison (Exported functions in PSM1 VS documented functions in PSD1)
  - [x] Integrity Check: Pester
  NOTE: Outcome is to be written into Change Log
  This might currently not really be very useful just yet (only very few files are tested - those that do not require a session to AzureAd, MicrosoftTeams, MgGraph - how to test those???). Additional tests will need to be written
  - [ ] Integrity Check: Function Status
  TODO:  `Get-FunctionStatus` compares Status of individual functions and displays this in Change log
  No longer useful or retain?
  - [ ] Sign PSM1 file with self-signed certificate - How to do that?
  Currently done manually and checked with `Update-DocsAndPester` before triggereing Pester tests
  - [x] Create Change Log
  Changes are currently collected in VERSION-PRERELEASE.md, upon release transferred to `VERSION.md` and manually copied into Release Notes for GitHub release.
  This will require thinking through automating reading from prepared file or taking Names of Commits?
  Update VERSION.md (from VERSION-PRERELEASE.md?) - currently manually collated; move to Read fro Commits?
  - [ ] Include Codacity scan and analysis?
  - [x] Create Release with Version (Trigger CD Mechanism)
  This will require some deliberation as Versioning is (deliberately) not aligned to Semantic versioning to allow a monthly release.
- [x] **Create CD Mechanism (currently manual)**
  - [x] Directory and
  - [x] Templating PSM1
  - [x] Templating PSD1 (Version Number comes from Release Substring)
  - [ ] Testing Deployment
    - [ ] Manually: Creating next release (v22.2 - one dot = release)
    - [ ] Manually: Creating next pre-release (v22.1.x - two dots = prerelease)
    Note: I didn't want to railroad myself into it like this, so have decided on this always manually. Versioning to be reviewed.
- [ ] Testing whole pipeline

**Comment by DEberhardt** [comment]
Not adopting SemVer now requires to come up with a way to "read" the version number. This is a good preparation step for the future anyway, but so far, deployment is stalled after BUILD/TEST/DOC, signing may be possible through secret, but deploy is so far hanging on the version number coming from somewhere.
Probably have to refactor this to be `OnRelease` rather than `OnPush` as well

**Comment by DEberhardt** [comment]
Update:
- Moved to SemVer, to make things easier (yes, I know)
- Automated deployment from PR to Main (needs changing to Deploy environment)
- Integrated Change log

Getting better with GitHub features, learning a lot from John Saville and making use of what I learned

**Comment by DEberhardt** [comment]
this module is sunset, so not further work is done on this. continuing on it with Orbit though
